
###
POST http://127.0.0.1:5000/api/v1/auth/login
content-type: application/json

{
    "username": "a",
    "password": "a"
}

###
GET http://127.0.0.1:5000/api/v1/auth/profile
Authorization: Bearer your_token_string


###
POST http://localhost:5000/api/v1/auth/refresh
Cookie: refreshToken=xxx